export default {
    addPlace:"/add-place",
    editAccount:"/edit-account",
    findAddress:"/find-address",
    graphql:"http://192.168.0.14:4000/graphql",
    havruta:"/havruta",
    home:"/",
    login:"/",
    phoneLogin:"/phone-login",
    places:"/places",
    ride:"/ride",
    settings:"/settings",
    socialLogin:"/social-login",
    trip:"/trip",
    verifyPhone:"/verify-phone",
};