export default {
    addPlace:"/add-place",
    addTopic:"/add-topic",
    editAccount:"/edit-account",
    findAddress:"/find-address",
    graphql:"http://localhost:4000/graphql",
    havruta:"/havruta",
    home:"/",
    login:"/",
    phoneLogin:"/phone-login",
    places:"/places",
    ride:"/ride",
    settings:"/settings",
    socialLogin:"/social-login",
    topic:"/topic",
    trip:"/trip",
    verifyPhone:"/verify-phone",
};